### ISSUE TITLE
Why not production?

### ISSUE THREAD

**Issue by robertlagrant** [ivanmorenoj/k8s-wireguard#2]
> WARNING: Only use this method in a development environment, don’t use in a production environment

I'm just wondering why this is - what about the setup is not production-ready?

Thanks, and nice work!

**Comment by ivanmorenoj** [comment]
Because of security, with this VPN you have access to the whole network within you k8s cluster. If you want to to use wireguard in production I recommend you to try this https://github.com/squat/kilo
