### ISSUE TITLE
I can't access the service ip through vpn, but I can access the pod ip, can you help me?

### ISSUE THREAD

**Issue by redstone1994** [ivanmorenoj/k8s-wireguard#3]
thanks

**Comment by ivanmorenoj** [comment]
Do you have connection with the internet using the vpn?
Do you have enabled the ip_forward in the host through sysctl?
Do you have any firewall enabled in your host?

Could you explain more?

**Comment by redstone1994** [comment]
> Do you have connection with the internet using the vpn? Do you have enabled the ip_forward in the host through sysctl? Do you have any firewall enabled in your host?
> 
> Could you explain more?

yes, I can access the internet,ip_forward and firewalld are all set , I can  ping the pod ip, it means the  route is working, 
just the service ip can't access through curl. so kube-dns can not access too ,  I am very confused

i set the DNS is kube-dns and a pulic DNS 
this is the client config
```
[Interface]
PrivateKey = xxxxx
ListenPort = 51820
Address = 10.13.13.2/32
DNS = 10.96.0.10, 114.114.114.114, default.svc.cluster.local, svc.cluster.local, cluster.local
MTU = 1370

[Peer]
PublicKey = xxxxx
AllowedIPs = 0.0.0.0/0
Endpoint = xxxxx:31820
```

**Comment by ivanmorenoj** [comment]
A service in kubernetes doesn't have the icmp protocol, so you can't ping to the service ip, instead try to use the nmap command to see if the service is running. For example, try to check if the dns service is working with the following commands:
```sh
nmap 10.96.0.10 -p 53 -Pn
dig @10.96.0.10 kubernetes.default.svc.cluster.local
curl -k https://kubernetes.default.svc.cluster.local:443
```
This is my output
![image](https://user-images.githubusercontent.com/19803598/155265123-377b1823-6184-4794-a109-74af4c202192.png)

**Comment by redstone1994** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/26979634/155280807-f82c4d50-6ca1-45dc-a940-233528a0e9b0.png">
<img width="753" alt="image" src="https://user-images.githubusercontent.com/26979634/155281561-0011d390-e7b8-4922-9643-69e44b7b7d58.png">
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/26979634/155281580-7ed9b49d-d677-4b47-8ef7-3b8ffb32c3c9.png">
I can't access kube-dns
`10.100.106.254` is nginx service ip, `10.0.0.170` is nginx pod ip, i can just access pod ip，Does this network plugin have anything to do with it? I use Cilium

**Comment by redstone1994** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/26979634/155282480-6e4e73c3-2ad6-4b49-a9b7-68fe506b65ee.png">

**Comment by redstone1994** [comment]
![image](https://user-images.githubusercontent.com/26979634/155284219-655cdbe9-da26-4c97-bfb7-f2def00437f5.png)

**Comment by ivanmorenoj** [comment]
Ok, could you try to make the same commands within the **wireguard** pod to see if the service network is reachable inside the pod:
```sh
kubectl exec -it <wireguard-pod> -- bash
# withing the pod
apt-get update && apt-get install nmap dnsutils -y
nmap 10.96.0.10 -p 53 -Pn
dig @10.96.0.10 kubernetes.default.svc.cluster.local +noall +short
curl -k https://kubernetes.default.svc.cluster.local:443
```
If that doesn't work either, you should try check your network plugin configuration, probably you have an active network policy that deny the access to any service IP CIDR

**Comment by redstone1994** [comment]
![image](https://user-images.githubusercontent.com/26979634/155442833-12ae3046-7d2b-47ba-a697-520ef4aa3795.png)
emmmm

**Comment by ivanmorenoj** [comment]
Ok, so you have access to the service network within the pod. Well the linuxserver docker image adds some iptables rules that forward the traffic between clients and server to the outside of the pod, you can see this rules with the following commands:
```sh
iptables -vL -t filter
iptables -vL -t nat
ip route show
```
![image](https://user-images.githubusercontent.com/19803598/155478622-be040d00-76ff-4383-92af-93e07a16340c.png)

You can debug the traffic to see if the outgoing traffic from the client to the service network is being `MASQURADE`(d)

```sh
kubectl exec -it <wireguard-pod> -- bash
# within the pod
apt-get update && apt-get install tcpdump -y
# capture the traffic from wg0 interface to service CIDR network
tcpdump -nn -i wg0 dst net <service network>

## open another terminal within the pod
# capture the traffic from eth0 interface to service CIDR network
tcpdump -nn -i eth0 dst net <service network>

## open another terminal within the pod
# watch iptables FORWARD and POSTROUTING traffic counters
watch -n 5 'iptables -nvL -t filter | grep -A 4 FORWARD; iptables -nvL -t nat | grep -A 3 POSTROUTING'

## On wireguard client
curl -k https://kubernetes.default.svc.cluster.local:443
```
![image](https://user-images.githubusercontent.com/19803598/155486760-6d56fc57-4211-4297-b3a4-de265de053e6.png)

The traffic from the `wg0` and the `eth0` should be the same (the only difference is the source ip) because is been `FORWAR`(ded) then `MASQURADE`(d) by the `POSTROUTING` rule on `iptables`, the counters should be increasing each time you execute the command `curl` on the remote client

**Comment by redstone1994** [comment]
![image](https://user-images.githubusercontent.com/26979634/155647391-a402ea60-13f4-480e-9b3e-938ad532e95f.png)
I am not good at iptables commands，Does the absence of the last two rules matter?

**Comment by redstone1994** [comment]
![image](https://user-images.githubusercontent.com/26979634/155667334-344b9636-3c4f-49f7-802f-a93564cce5cd.png)
![image](https://user-images.githubusercontent.com/26979634/155667394-e0fd3df0-0a94-4692-ba45-f5db18a78456.png)
![image](https://user-images.githubusercontent.com/26979634/155667429-9d706124-a040-460a-ac9b-5b55f6d73c51.png)

**Comment by ivanmorenoj** [comment]
As I can see the DNS service is working with a remote wireguard client, I think your problem is with your network plugin

**Comment by redstone1994** [comment]
Thanks a lot, maybe I should try another  network plugin

**Comment by cornbuddy** [comment]
@redstone1994 did you manage to resolve your issues? Because I'm experiencing the same one :D
@ivanmorenoj why do you do that CNI is a subject to blame in this case? It seems like traffic is not forwarded to wireguard interface when request to service is made

**Comment by cornbuddy** [comment]
Well, it seems like @ivanmorenoj is right. When I enabled kube-proxy clusterwide and tune cilium's configuration to not replace kube-proxy, everything began to work
<img width="1631" alt="Screenshot 2022-03-22 at 07 20 26" src="https://user-images.githubusercontent.com/8258097/159401841-a419e412-16e1-4501-acff-89974ec82a01.png">
And on client side:
<img width="419" alt="Screenshot 2022-03-22 at 07 26 42" src="https://user-images.githubusercontent.com/8258097/159401979-0658eb20-cffe-4bfb-8a1f-25d90da07a11.png">

**Comment by redstone1994** [comment]
> @redstone1994 did you manage to resolve your issues? Because I'm experiencing the same one :D @ivanmorenoj why do you do that CNI is a subject to blame in this case? It seems like traffic is not forwarded to wireguard interface when request to service is made

i use the cilium with no kube-proxy,maybe the iptables not work

**Comment by lostrain** [comment]
> Ok, so you have access to the service network within the pod. Well the linuxserver docker image adds some iptables rules that forward the traffic between clients and server to the outside of the pod, you can see this rules with the following commands:
> 
> ```shell
> iptables -vL -t filter
> iptables -vL -t nat
> ip route show
> ```
> 
> ![image](https://user-images.githubusercontent.com/19803598/155478622-be040d00-76ff-4383-92af-93e07a16340c.png)
> 
> You can debug the traffic to see if the outgoing traffic from the client to the service network is being `MASQURADE`(d)
> 
> ```shell
> kubectl exec -it <wireguard-pod> -- bash
> # within the pod
> apt-get update && apt-get install tcpdump -y
> # capture the traffic from wg0 interface to service CIDR network
> tcpdump -nn -i wg0 dst net <service network>
> 
> ## open another terminal within the pod
> # capture the traffic from eth0 interface to service CIDR network
> tcpdump -nn -i eth0 dst net <service network>
> 
> ## open another terminal within the pod
> # watch iptables FORWARD and POSTROUTING traffic counters
> watch -n 5 'iptables -nvL -t filter | grep -A 4 FORWARD; iptables -nvL -t nat | grep -A 3 POSTROUTING'
> 
> ## On wireguard client
> curl -k https://kubernetes.default.svc.cluster.local:443
> ```
> 
> ![image](https://user-images.githubusercontent.com/19803598/155486760-6d56fc57-4211-4297-b3a4-de265de053e6.png)
> 
> The traffic from the `wg0` and the `eth0` should be the same (the only difference is the source ip) because is been `FORWAR`(ded) then `MASQURADE`(d) by the `POSTROUTING` rule on `iptables`, the counters should be increasing each time you execute the command `curl` on the remote client

Hi, I met the same problem, I have followed your discussions above, it seem that:
If I disconnect from vpn and exec 'curl -k https://kubernetes.default.svc.cluster.local:443' in wireguard pod, there are traffics in `tcpdump -nn -i eth0 dst net <service network>` , but not traffic in `tcpdump -nn -i wg0 dst net <service network>`;
If I connect to vpn, there are traffics in wg0 but not traffic in eth0. And if I exec 'curl -k https://kubernetes.default.svc.cluster.local:443' in wireguard pod, just like above, there are traffics in eth0 but no traffic in wg0.
Where may be the problem?
